// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:75b2adcd-1704-4996-bd37-1dc5ca828731",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_qq3sAkS75",
    "aws_user_pools_web_client_id": "6vtncoktu46n5rith8dm504g17",
    "oauth": {},
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://ycbvsspcfvg2hk4xdvfyacxb2u.appsync-api.eu-central-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-central-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "e7e8b9f6938540f39c075a85da2f4f9e",
    "aws_mobile_analytics_app_region": "eu-central-1"
};


export default awsmobile;
