// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:48657586-2a8b-4891-b0fc-23d119fdd9d7",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_gEjaFyt2U",
    "aws_user_pools_web_client_id": "529nij9k9b701tl7981hg592u2",
    "oauth": {
        "domain": "eventgo-dev.auth.eu-central-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "myapp://",
        "redirectSignOut": "myapp://",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_mobile_analytics_app_id": "e7e8b9f6938540f39c075a85da2f4f9e",
    "aws_mobile_analytics_app_region": "eu-central-1"
};


export default awsmobile;
